### PR TITLE
Fix shader updates

### PR DESCRIPTION
**Pull request by adamhutchings**

### CODE REVIEW

**Comment by Sophon96** [comment]
What was the original issue?

**Comment by adamhutchings** [comment]
I tested and found that if we rendered using the game shader, the square would rapidly recede into the distance. Now we make sure to bind the correct shader before updating its uniforms.

**Review by Sophon96 — APPROVED** [review]
Ah, LGTM.

**Review by JakeRoggenbuck — APPROVED** [review]
Great

**Pull request merged**
