### PR TITLE
Add image

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**

### CODE REVIEW

**Review by adamhutchings — APPROVED** [review]
Pog!

**Comment by Sophon96** [comment]
What is the point of this?

**Comment by Sophon96** [comment]
This is just a png file

**Comment by JakeRoggenbuck** [comment]
need image to work with

**Comment by Sophon96** [comment]
Oh, ok.

**Review by Sophon96 — APPROVED** [review]
Is there anything to really review?

**Pull request merged**
